### ISSUE TITLE
Will there be a map aerial view available?

### ISSUE THREAD

**Issue by vinhk** [zoharby/plot_google_map#10]
Hi,
I am wondering if you have feature for actual aerial view of the map. I would like to see buildings and actual objects when zooming in. Or if you could give me some direction to implement that from your repository.

Thanks

**Comment by zoharby** [comment]
Hi, you can use:
`plot_google_map('maptype','satellite')`
to display satellite imagery instead of a road map.

**Comment by vinhk** [comment]
awesome
