### ISSUE TITLE
Implement the scale with specified fontname/fontsize

### ISSUE THREAD

**Issue by YangRiverJiang** [zoharby/plot_google_map#15]
Hello,

Really appreciate your code! Can we have specified fontname/fontsize properties for the scale ruler on the map in the future?

https://github.com/zoharby/plot_google_map/blob/6a7991e36fbb2e11111cb423d72b9294c6b3f8c1/makescale.m#L206

River

**Comment by zoharby** [comment]
Hi,

I'm not really maintaining this code anymore. Feel free to add this in a Pull Request and I'll be happy to merge it.
