### ISSUE TITLE
plot_google_map cannot be used in standalone compiled Matlab programs.

### ISSUE THREAD

**Issue by cbcunc** [zoharby/plot_google_map#2]
Standalone compiled Matlab programs have a default path wherever they are installed. For most OSes, writing to the program installation directory (\Program Files for Windows; /Applications for OSX) is a privileged operation. For normal users this will fail. Most OSes provide a directory for temporary files generated by user programs, as well as an API to find it. Matlab provides the cross-platform tempdir function for this purpose. PR #1 allows plot_google_map to be used in standalone compiled Matlab programs.

**Comment by zoharby** [comment]
Solved by merging the PR
