### ISSUE TITLE
problem with the color bar in plot_google_map

### ISSUE THREAD

**Issue by kailas29** [zoharby/plot_google_map#4]
Hi,

I am plotting a contour with a color bar and everything works fine the colour bar has the appropriate limits etc. Then when i am adding the get_google_map command it changes/ overwrites the colorbar  do you have any ideas why?

Cheeers

**Comment by zoharby** [comment]
Can you please supply a short sample code to reproduce your problem? 
What MATLAB version are you using?

**Comment by kailas29** [comment]
2016b I found the solution... posting it below in case you think its useful

figure
contour(Y,X,Z,contLevel,'ShowText','on'); hold on %contourf if i need filled contour
colormap(jet)
colorbar
% Google map
plot_google_map('maptype', 'satellite')

This one changes the colorbar from contour to the default colorbar 
I added: 
mesh(X,Y,Z); % interpolated

and now it seems to work fine

**Comment by zoharby** [comment]
This is really a bug in the new MATLAB graphics system.
It seems to simply ignore the caxis setting in this case, and always shows the colorbar with range 1-65.
Tried to find a workaround, but couldn't find any viable solution.

**Comment by kailas29** [comment]
Exactly.  I had the same problem thats why I posted in your GitHub. In any case it works if you add a mesh

**Comment by esteban11** [comment]
Had the same issue, and got it solved by replacing an older version plot_google_map with this: https://www.mathworks.com/matlabcentral/fileexchange/27627-zoharby-plot-google-map

**Comment by zoharby** [comment]
Solved by latest commit. Thanks to Patrick Monsere for the solution.
