### ISSUE TITLE
problem on zooming

### ISSUE THREAD

**Issue by FranciiscoSilva** [zoharby/plot_google_map#5]
Hi, im trying to plot my university on the map.
However as i only give them one point to center .(one lat,long) he plots me almost all my country. i wish to know how can i call the plot_google_map and still control his zoom level without giving any error...

thanks

**Comment by zoharby** [comment]
Hi,

Zoom level is not determined by the function. Instead, it simply uses the current axis span of your plot (with some adaptions to make sure map isn't stretched in one axis).
when you plot just a single point, e.g. `plot(long,lat)` the default is a very wide span. You can change it with the `axis` command, for example:
```
plot(long,lat)
axis([long-0.01 long+0.01 lat-0.01 lat+0.01])
plot_google_map()
```

**Comment by FranciiscoSilva** [comment]
yeah, i already done that. realized they need to know more than one location to define the tiles zooms. so i had an extra point. tough that axis formula is very wise ...
Thanks a lot.
