### ISSUE TITLE
How to set a different satellite image date to be plotted ? 

### ISSUE THREAD

**Issue by alexandre-loureiro** [zoharby/plot_google_map#6]
Hi,

I need some help :-)
How can I plot a Google Earth satellite image using an image date from 2015.
How can I do it using your code plot_google_map.m ?
I found 4 sites below which explains something about it, but I don´t know how to do it:
1) ee.Filter.date()
https://developers.google.com/earth-engine/api_docs#eefilterdate
2) ee.image.date()
https://developers.google.com/earth-engine/api_docs#eeimagedate
3) ge.getTime().getControl().getAvailableImageDates()
https://stackoverflow.com/questions/11748525/how-to-get-date-of-currently-displayed-imagery-in-the-google-earth-api
4) imageCollection.filterDate()
https://developers.google.com/earth-engine/ic_filtering

**Comment by zoharby** [comment]
Hi,

plot_google_map uses the Static Maps API, which does not support this.
So unfortunately, this is not possible in plot_google_map.

**Comment by alexandre-loureiro** [comment]
Hi Zohar,

Do you know where I can found information about how to set a different
satellite image date to be plotted ?

best regards
Alexandre
