### ISSUE TITLE
Where I can find information about how to set a different satellite image date to be plotted ?

### ISSUE THREAD

**Issue by alexandre-loureiro** [zoharby/plot_google_map#7]
Hi Zohar,

Do you know where I can found information about how to set a different satellite image date to be plotted ?
There is another API ?

best regards
Alexandre

**Comment by zoharby** [comment]
As far as I know, this is not supported by any Google API, and is only available in Google Street View on the Google Maps website.
I don't think such a feature exists for satellite imagery.
