### ISSUE TITLE
Reset axes, axes parent, zoom, pan

### ISSUE THREAD

**Issue by matlabor** [zoharby/plot_google_map#9]
When I delete the gmap handle created with:

```
figure
ax = axes
h = plot_google_map(ax)
delete(h)
```

the `ActionPostCallback` of the zoom and pan handles `z = zoom(axes);` is not set to its original empty state. This leads to plotting the google map again when zooming in or out.

How can I fully reset the axes without deleting any other children they might contain?
And how to return to the original state of the axes parent?

**Comment by zoharby** [comment]
Fixed in latest commit. Notes:

1. The correct syntax is:
```
h = plot_google_map('axis', ax)
```
2. `delete(h)` will only work if you haven't panned/zoomed the map (in which case the image is erased and a new one is being drawn, hence `h` would point to a deleted object). This would work even after zooms:
```
delete(findobj(get(ax, 'Children'), 'tag', 'gmap'))
```
